version = 1

[[annotations]]
path = "Cargo.toml"
SPDX-FileCopyrightText = "2023-2026 Ali Polatel <alip@chesswob.org>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
